// <auto-generated />
using System;
using Fiscal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiscal.Infrastructure.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    [Migration("20260919171912_AddEmitenteFiscal")]
    partial class AddEmitenteFiscal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiscal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Entity")
                        .HasDatabaseName("IX_audit_log_tenant_entidade");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("IX_audit_log_tenant_ocorrido");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.ConcessaoUnidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Papel")
                        .HasColumnType("integer")
                        .HasColumnName("papel");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_concessoes_tenant_user");

                    b.HasIndex("TenantId", "BranchId", "UserId", "Papel")
                        .IsUnique()
                        .HasDatabaseName("UX_concessoes_tenant_branch_user_papel_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("concessoes_unidade", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.ConfiguracaoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("ambiente");

                    b.Property<string>("CscId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("csc_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid>("EmitenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("emitente_id");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean")
                        .HasColumnName("habilitado");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("ModoIntegracao")
                        .HasColumnType("integer")
                        .HasColumnName("modo_integracao");

                    b.Property<Guid?>("ReferenciaCertificado")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_certificado");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("serie");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmitenteId")
                        .HasDatabaseName("IX_config_doc_emitente");

                    b.HasIndex("EmitenteId", "Tipo", "Ambiente")
                        .IsUnique()
                        .HasDatabaseName("UX_config_doc_emitente_tipo_amb_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("configuracoes_documento", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.EmitenteFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Cnae")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("cnae");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Crt")
                        .HasColumnType("integer")
                        .HasColumnName("crt");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fantasia");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_emitentes_tenant_id");

                    b.HasIndex("TenantId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UX_emitentes_tenant_branch_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("emitentes_fiscais", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique()
                        .HasDatabaseName("UX_municipios_ibge_active")
                        .HasFilter("\"is_active\"");

                    b.HasIndex("Uf")
                        .HasDatabaseName("IX_municipios_uf");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.NfseAmbiente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("ambiente");

                    b.Property<string>("BaseUrlAdn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url_adn");

                    b.Property<string>("BaseUrlParametros")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url_parametros");

                    b.Property<string>("BaseUrlSefin")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url_sefin");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Modo")
                        .HasColumnType("integer")
                        .HasColumnName("modo");

                    b.Property<bool>("Verificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verificado");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge", "Modo", "Ambiente")
                        .IsUnique()
                        .HasDatabaseName("UX_nfse_ambientes_ibge_modo_amb_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("nfse_ambientes", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.NfseImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArquivoHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("arquivo_hash");

                    b.Property<int>("Atualizados")
                        .HasColumnType("integer")
                        .HasColumnName("atualizados");

                    b.Property<int>("Criados")
                        .HasColumnType("integer")
                        .HasColumnName("criados");

                    b.Property<int>("IgnoradosManuais")
                        .HasColumnType("integer")
                        .HasColumnName("ignorados_manuais");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<int>("Rejeitados")
                        .HasColumnType("integer")
                        .HasColumnName("rejeitados");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OcorridoEm")
                        .HasDatabaseName("IX_nfse_import_runs_ocorrido");

                    b.ToTable("nfse_import_runs", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.NfseMunicipioConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_ibge");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Fonte")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fonte");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Modo")
                        .HasColumnType("integer")
                        .HasColumnName("modo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<bool>("SobrescritoManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sobrescrito_manual");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique()
                        .HasDatabaseName("UX_nfse_municipio_configs_ibge_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("nfse_municipio_configs", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.SefazEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("ambiente");

                    b.Property<string>("Autorizador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("autorizador");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("FonteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fonte_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Modelo")
                        .HasColumnType("integer")
                        .HasColumnName("modelo");

                    b.Property<int>("Servico")
                        .HasColumnType("integer")
                        .HasColumnName("servico");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<bool>("Verificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("verificado");

                    b.Property<DateTime?>("VerificadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificado_em");

                    b.Property<string>("VersaoServico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_servico");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id");

                    b.HasIndex("Autorizador")
                        .HasDatabaseName("IX_sefaz_endpoints_autorizador");

                    b.HasIndex("Autorizador", "Ambiente")
                        .HasDatabaseName("IX_sefaz_endpoints_autorizador_ambiente");

                    b.HasIndex("Autorizador", "Modelo", "Servico", "Ambiente", "VersaoServico")
                        .IsUnique()
                        .HasDatabaseName("UX_sefaz_endpoints_natural_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("sefaz_endpoints", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.UfFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AutorizadorNFCe")
                        .HasColumnType("integer")
                        .HasColumnName("autorizador_nfce");

                    b.Property<int>("AutorizadorNFe")
                        .HasColumnType("integer")
                        .HasColumnName("autorizador_nfe");

                    b.Property<int>("CodigoIbge")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_ibge");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique()
                        .HasDatabaseName("UX_ufs_fiscais_cuf_active")
                        .HasFilter("\"is_active\"");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("UX_ufs_fiscais_sigla_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("ufs_fiscais", (string)null);
                });

            modelBuilder.Entity("Fiscal.Domain.Entities.EmitenteFiscal", b =>
                {
                    b.OwnsOne("Fiscal.Domain.ValueObjects.CnpjFiscal", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("EmitenteFiscalId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Alfanumerico")
                                .HasColumnType("boolean")
                                .HasColumnName("cnpj_alfanumerico");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("EmitenteFiscalId");

                            b1.ToTable("emitentes_fiscais");

                            b1.WithOwner()
                                .HasForeignKey("EmitenteFiscalId");
                        });

                    b.OwnsOne("Fiscal.Domain.ValueObjects.FiscalAddress", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("EmitenteFiscalId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("end_cidade");

                            b1.Property<string>("CodigoIbgeMunicipio")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("end_ibge");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("end_complemento");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("end_bairro");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("end_numero");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("end_cep");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("end_uf");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("end_logradouro");

                            b1.HasKey("EmitenteFiscalId");

                            b1.ToTable("emitentes_fiscais");

                            b1.WithOwner()
                                .HasForeignKey("EmitenteFiscalId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
