// <auto-generated />
using System;
using Estoque.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estoque.Infrastructure.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20260822190930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estoque.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("GeneratedOn")
                        .HasColumnType("date")
                        .HasColumnName("generated_on");

                    b.Property<Guid?>("LotIdRef")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("IX_alerts_tenant_created_at");

                    b.HasIndex("TenantId", "Type", "ProductId", "BranchId", "GeneratedOn")
                        .IsUnique()
                        .HasDatabaseName("UX_alerts_dedupe")
                        .HasFilter("\"product_id\" IS NOT NULL AND \"branch_id\" IS NOT NULL");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_brands_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_brands_tenant_name_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_categories_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_categories_tenant_name_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExpiresOn")
                        .HasDatabaseName("IX_lots_tenant_expires_on");

                    b.HasIndex("TenantId", "BranchId", "ProductId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_lots_tenant_branch_product_number_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_models_tenant_id");

                    b.HasIndex("TenantId", "BrandId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_models_tenant_brand_name_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.OutletItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<int>("SuggestedDiscountPct")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_discount_pct");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_outlet_items_tenant_id");

                    b.HasIndex("TenantId", "BranchId", "ProductId")
                        .HasDatabaseName("IX_outlet_items_tenant_branch_product");

                    b.ToTable("outlet_items", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("barcode");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("integer")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_products_tenant_id");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("UX_products_tenant_barcode_active")
                        .HasFilter("\"is_active\" AND \"barcode\" IS NOT NULL");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_products_tenant_sku_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.PurchaseSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<decimal>("ObservedBalance")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("observed_balance");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("SuggestedQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("suggested_quantity");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_purchase_suggestions_tenant_id");

                    b.HasIndex("TenantId", "ProductId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UX_purchase_suggestions_open")
                        .HasFilter("\"status\" = 1");

                    b.ToTable("purchase_suggestions", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AverageUnitCost")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("average_unit_cost");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProductId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UX_stock_balances_tenant_product_branch");

                    b.ToTable("stock_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_balances_quantity_non_negative", "\"quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Estoque.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CounterpartyBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("OriginDocumentRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origin_document_ref");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("IX_stock_movements_tenant_created_at");

                    b.HasIndex("TenantId", "BranchId", "ProductId")
                        .HasDatabaseName("IX_stock_movements_tenant_branch_product");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.StockRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<decimal>("MinimumQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_quantity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reorder_point");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_stock_rules_tenant_id");

                    b.HasIndex("TenantId", "ProductId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UX_stock_rules_tenant_product_branch_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("stock_rules", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pessoa");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_suppliers_tenant_id");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_suppliers_tenant_document_active")
                        .HasFilter("\"is_active\"");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.XmlImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("integer")
                        .HasColumnName("processed_items");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("SkippedItems")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_items");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_xml_imports_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_xml_imports_tenant_id");

                    b.ToTable("xml_imports", (string)null);
                });

            modelBuilder.Entity("Estoque.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("IX_outbox_messages_pending");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Estoque.Domain.Entities.Supplier", b =>
                {
                    b.OwnsOne("Estoque.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_district");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("address_street");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("Estoque.Domain.ValueObjects.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("contact_phone");

                            b1.Property<string>("SecondaryPhone")
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("contact_secondary_phone");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
